// ============================================================
// CONFIGURAZIONE WEEKEND DA PENDOLI
// Modifica qui i dati — l'HTML si aggiorna automaticamente
// ============================================================

// Righe della tabella comparativa (nell'ordine in cui appaiono)
// card: true  → appare anche nella griglia statistiche della card
// emoji       → icona usata nella card (solo se card: true)
const tableRows = [
  { label: 'Tappe',               key: 'tappe',         emoji: '📍', unit: 'Tappe',   card: true  },
  { label: 'Eventi',              key: 'eventi',        emoji: '🎉', unit: 'Eventi',  card: true  },
  { label: 'Km percorsi',         key: 'km',            emoji: '🛣️', unit: 'Km',      card: true  },
  { label: 'Ore di viaggio',      key: 'viaggio',       emoji: '⏱️', unit: '',        card: true  },
  { label: 'Numero notti',        key: 'notti',         card: false },
  { label: 'Numero alloggi',      key: 'alloggi',       card: false },
  { label: 'Sonno in viaggio',    key: 'sonnoViaggio',  card: false },
  { label: 'Sonno totale',        key: 'sonno',         card: false },
  { label: 'Ore di veglia (ca.)', key: 'veglia',        card: false },
  { label: 'Ore nel chill (ca.)', key: 'chill',         card: false },
  { label: 'Costo per persona',   key: 'costo',         card: false },
  { label: 'Tempo libero',        key: 'tempoLibero',   card: false },
];

const options = [
  {
    id: 'ultra',
    title: 'Weekend Ultra Pendolante',
    subtitle: 'Milano – Roma – Lido – Milano',
    tableLabel: 'Weekend Ultra Pendolante',
    stats: {
      tappe:        '4',
      eventi:       '3',
      km:           '1.596',
      viaggio:      '21:50h',
      notti:        '3',
      alloggi:      '1',
      sonnoViaggio: '9:55h',
      sonno:        '26:15h',
      veglia:       '24h',
      chill:        '13h',
      costo:        '€ 146,00',
      tempoLibero:  '52,26%',
    },
    itinerary: [
      '<strong>30 Apr:</strong> Brescia →🚗→ Milano (1D Night)',
      '<strong>1 Mag:</strong> Milano →🚗+🚌→ Roma (Concertone 1° Maggio) →🚌🌙→ Lido (viaggio in notturna)',
      '<strong>2 Mag:</strong> Lido (mare nel chill) →🚗→ Milano (arrivo in serata)',
      '<strong>3 Mag:</strong> Stramilano/Milano nel chill →🚗→ Ritorno a Brescia/Desenzano',
    ],
    pros: ['Crazy as fuck', 'Costo basso'],
    cons: ['Molte ore di viaggio (22h)', '2x nanne in viaggio'],
    price: '~ € 146,00',
  },
  {
    id: 'molto',
    title: 'Weekend Molto Pendolante',
    subtitle: 'Lido – Roma – Lido – Milano',
    tableLabel: 'Weekend Molto Pendolante',
    stats: {
      tappe:        '4',
      eventi:       '2',
      km:           '1.585',
      viaggio:      '22:10h',
      notti:        '3',
      alloggi:      '2',
      sonnoViaggio: '4:40h',
      sonno:        '26:40h',
      veglia:       '24h',
      chill:        '13h',
      costo:        '€ 136,88',
      tempoLibero:  '53,96%',
    },
    itinerary: [
      '<strong>30 Apr:</strong> Brescia →🚗→ Lido',
      '<strong>1 Mag:</strong> Lido →🚌→ Roma (chill + Concertone 1° Maggio) →🚌🌙→ Lido (viaggio in notturna)',
      '<strong>2 Mag:</strong> Lido (mare nel chill) →🚗→ Milano (arrivo in serata)',
      '<strong>3 Mag:</strong> Stramilano/Milano nel chill →🚗→ Ritorno a Brescia/Desenzano',
    ],
    pros: ['Grande varietà ed epicità', 'Costo più basso'],
    cons: ['Molte ore di viaggio (22h)', 'Nanne in viaggio'],
    price: '~ € 136,88',
  },
  {
    id: 'abbastanza',
    title: 'Weekend Abbastanza Pendolante',
    subtitle: 'Lido – Roma – Lido',
    tableLabel: 'Weekend Abbastanza Pendolante',
    stats: {
      tappe:        '3',
      eventi:       '1',
      km:           '1.360',
      viaggio:      '18:30h',
      notti:        '3',
      alloggi:      '1',
      sonnoViaggio: '4:40h',
      sonno:        '27:40h',
      veglia:       '26h',
      chill:        '21h',
      costo:        '€ 246,88',
      tempoLibero:  '79,35%',
    },
    itinerary: [
      '<strong>30 Apr:</strong> Brescia →🚗→ Lido',
      '<strong>1 Mag:</strong> Lido →🚌→ Roma (Concertone 1° Maggio) →🚌🌙→ Lido (viaggio in notturna)',
      '<strong>2 Mag:</strong> Lido (mare nel chill)',
      '<strong>3 Mag:</strong> Lido (mare nel chill) →🚗→ Ritorno a Brescia/Desenzano',
    ],
    pros: ['2 giorni di mare'],
    cons: ['Molte ore di viaggio (18h)', 'Nanne in viaggio', 'Costo più alto'],
    price: '~ € 246,88',
  },
  {
    id: 'appena',
    title: 'Weekend Appena Pendolante',
    subtitle: 'Roma – Milano',
    tableLabel: 'Weekend Appena Pendolante',
    stats: {
      tappe:        '2',
      eventi:       '2',
      km:           '1.220',
      viaggio:      '9:45h',
      notti:        '3',
      alloggi:      '2',
      sonnoViaggio: '0',
      sonno:        '32h',
      veglia:       '31h',
      chill:        '21h',
      costo:        '€ 236,00',
      tempoLibero:  '67,77%',
    },
    itinerary: [
      '<strong>30 Apr:</strong> Desenzano →🚗/🚅→ Roma',
      '<strong>1 Mag:</strong> Roma (chill + Concertone 1° Maggio)',
      '<strong>2 Mag:</strong> Roma nel chill →🚗/🚅→ Milano (arrivo in serata)',
      '<strong>3 Mag:</strong> Stramilano/Milano nel chill →🚗/🚅→ Ritorno a Desenzano',
    ],
    pros: ['Molte ore di sonno (32h)', 'Costo medio-alto', 'Miglior rapporto tappe-eventi'],
    cons: ['Niente mare'],
    price: '~ € 236,00',
  },
  {
    id: 'non',
    title: 'Weekend Non Pendolante',
    subtitle: 'Roma',
    tableLabel: 'Weekend Non Pendolante',
    stats: {
      tappe:        '1',
      eventi:       '1',
      km:           '1.050',
      viaggio:      '7:52h',
      notti:        '3',
      alloggi:      '1',
      sonnoViaggio: '0',
      sonno:        '32h',
      veglia:       '32h',
      chill:        '21h',
      costo:        '€ 256,00',
      tempoLibero:  '63,80%',
    },
    itinerary: [
      '<strong>30 Apr:</strong> Desenzano →🚗/🚅→ Roma',
      '<strong>1 Mag:</strong> Roma (chill + Concertone 1° Maggio)',
      '<strong>2 Mag:</strong> Roma nel chill',
      '<strong>3 Mag:</strong> Roma nel chill →🚗/🚅→ Ritorno a Desenzano',
    ],
    pros: ['Molte ore di sonno (32h)', 'Daje Roma daje (3 giorni a Roma)'],
    cons: ['Costo massimo', 'Bassa epicità (1 tappa, no mare)'],
    price: '~ € 256,00',
  },
];
